### ISSUE TITLE
Suggested updates

### ISSUE THREAD

**Issue by fhilipk** [Project-Catalyst/proposal-review-tool#11]
After entry two buttons are presented 'Next' and 'overview'.

Rename 'overview' to 'assessments' or 'assessments list/overview'.

Add UI element that shows 'flags' on overview page

On overview page naxt to 'next' 'close list' add an 'export button'

Add 'Instructions' as a menu item

Make menu viable on every page - currently

**Comment by jbmattos** [comment]
- [ ] After entry two buttons are presented 'Next' and 'overview'. Rename 'overview' to 'assessments' or 'assessments list/overview'.
- [ ] Add UI element that shows 'flags' on overview page
- [ ] On overview page, next to 'next' 'close list' add an 'export button'
- [ ] Add 'Instructions' as a menu item
- [ ] Make menu viable on every page - currently

**Comment by fhilipk** [comment]
Example of 'Flag'
![image](https://user-images.githubusercontent.com/6503797/159343925-03b74d59-af83-4cbc-98b1-4bfb20d13b7d.png)

**Comment by fhilipk** [comment]
![image](https://user-images.githubusercontent.com/6503797/159344164-0a7c4615-efdd-41ad-a1bb-1e21d144a1bf.png)

**Comment by jbmattos** [comment]
### "Save / Export CSV" button not working on Assessments page
The button in Conditions.vue was implemented according to the one in Profile.vue.
_Tracing back the problem_:
When running download.exportCsv() calling from the Conditions button, the object this.assessments is undefined (differently from when the same method is called by Profile or by the navigation bar).

**Comment by jbmattos** [comment]
### Flags always false
When loading the Assessment's page of "assessment.id=2", for example, _this.assessment.not_valid_ is rightfully loaded (according to the user's choice):
![image](https://user-images.githubusercontent.com/43577084/159535998-d8ad1904-7a2f-46d8-9473-4b3f7d85db07.png)

However, when loading the AssessmentPreview, _this.assessment.not_valid_ always assume _false_ (independently from the value that is loaded in Assessment).
Thus, the flags added to the assessments preview are always unchecked.
![image](https://user-images.githubusercontent.com/43577084/159537099-a1dc42d2-c389-4c54-8137-08899c0ba113.png)

**Comment by fhilipk** [comment]
@jbmattos Can you also change the name 'Flagged' to 'Filtered Out'. I think it's better to keep the same naming... also I don't think the UX should allow 'checking' (in case that box currently a boolean) of this box on the overview, as this might encourage the use case of flagging even reading or even looking at the assessments.

**Comment by fhilipk** [comment]
I'm not sure if we have an icon set already available @coire1 might know. I'd prefer if a flag or similar icon with perhaps the words 'Filtered Out' next to it was included.

**Comment by fhilipk** [comment]
Update copy - Assessment page: Change "Your rationale for the report OR your feedback to CA if not reported:" to "Provide your rationale for reporting OR your feedback to CA if not reported:"

**Comment by coire1** [comment]
Hey @jbmattos, I pushed a small update on your branch that should fix the issue.
The problem was that the dataset used by `AssessmentPreview` (`renderedList` getter that depends on `FulAssessments` getter) didn't include the values saved in the local storage.
With the last commit, every assessment in `fullAssessments` is merged with the corresponding assessment in `indexed` getter that depends on `state.all` which is the place where we store the values modified by users.
This complex behavior depends by the fact that we need to limit the amount of data to be stored in `localStorage`, due to browser limitation.
For this reason we have 2 main data sources: 
1. the original assessments, which is a static copy with all the info about assessments, and is loaded only in memory and it is not modified
2. the local assessments modifiable by the user, which include only the `id`, `not_valid` and `not_valid_rationale`

Then, when we need to display everything, we merge these two data sources and we have the full data.
Hope i was clear even if i used like 1000 times the word `assessment` :P

**Comment by jbmattos** [comment]
> @jbmattos ~Can you also change the name 'Flagged' to 'Filtered Out'~ (changed my mind). I think it's better to keep the same naming... Can you change 'Filtered out' to 'Yes, flag this assessment'.
> 
> Also the also I don't think the UX should allow 'checking' (in case that check box in your Dev Environment is currently a boolean) of this box on the overview, as this might encourage the use case of flagging without reading or even looking at the assessments.

Hey @fhilipk, 
The idea is to the checkbox on the Overview page to be disabled. The "Filtered out" assessments would appear to be "checked", but the checkbox itself cannot be checked. Is just a way of displaying this flag (in the VCA tool some flags are displayed like that too). I agree that naming the checkbox to "Filtered out" makes it clearer the relation with the "Filtered out" option on the Assessment page.

I uploaded the adjusted version using the disabled checkbox, and it looks like below:
![current_view](https://user-images.githubusercontent.com/43577084/159684024-ff7110d9-9e26-459d-b3b3-a478b2b0bb50.png)

Alternatively, we can use the flag icon, and it would look like this:
![flag_view](https://user-images.githubusercontent.com/43577084/159684151-e86be6a1-2eda-44e4-a41e-8a7e15e4e450.png)
Let me know if you prefer the flag, that I upload its code.

**Comment by fhilipk** [comment]
The issue I'm having is the a checkbox has meaning - and it breaks that context to disable it. Maybe the Flag icon with the words "Flagged review requested".

The trick is that a 'proposer' I can't filter out anything - that's for the vCAs to do. So I'm trying to get the wording right.

**Comment by jbmattos** [comment]
Great @fhilipk!
I've just uploaded the new view:
![flag_view](https://user-images.githubusercontent.com/43577084/159690330-fe69fe5a-b29f-428e-8a2b-efceb660cfdf.png)

**Comment by fhilipk** [comment]
This is great. Thank you.

**Comment by jbmattos** [comment]
Opened issue #14 to address specifically the 'export button' required in this issue.
