### ISSUE TITLE
Update process content

### ISSUE THREAD

**Issue by fhilipk** [Project-Catalyst/proposal-review-tool#9]
Remove
"1. From the QA proposers email you'll receive the Google Sheet link for the Proposers Master File: instead of following the standard procedure, save the Proposer Master File as a CSV (File -> Download -> Comma-separated value)."

Update to
1. Click on the "Start Process" button."
2. On the next screen fill in your details: "IdeaScale username" & "email address". Choose an option to start your process:
2a. "I want to start the process from the beginning,  I don't have a backup file to import." This create a clean review space.
or
2b" I want to continue the process, I have a backup file to import." This will allow you to import a previous session.
3. Search for and select your proposals (please only review the proposals you are a proposer on).
4. Review the CA assessment, if it is acceptable continue with your next proposal or finish the process. If it requires attention from the Community QA participants (vCAs) flag it and provide your reason for doing so.
5.  When your review is complete from the menu click "Export CSV", save the file.
6. Submit your export file before the deadline by filling in this form: XXXXXXX NEW FORM XXXXXX

**Comment by coire1** [comment]
- [ ] Add final FORM link
